### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by vrimar** [vrimar/construct-ui#4]
### General changes
- [ ] Update to mithril 2.x
- [ ] Add support for alternative icon libraries (i.e material icons)
- [ ] Add dark theme

### New components
- [ ] Calendar
- [ ] CalendarSelect
- [ ] CSS Tooltip
- [ ] EditableText
- [ ] InputNumber
- [ ] Pagination
- [ ] PopoverConfirm
- [ ] Progress
- [ ] Slider
- [ ] TagInputSelect
- [ ] TreeSelect

### Docs
- [ ] Archive older versions
- [ ] Add plain JS examples

**Comment by boazblake** [comment]
is this project dead?

**Comment by panoply** [comment]
@boazblake I don't believe it's dead but I have tried to reach out to @vrimar a couple times now with no luck. If it is dead, I'll likely hard-fork because we leverage it internally in our ERP and it's rather essential to that.

There are several aspects to the project that I'd like to refactor.

**Comment by boazblake** [comment]
@panoply Hi! 

Thats too bad - hopefully @vrimar comes back - do you use this with v2 of mithrilJS or v1? 
I was trying to incorporate it into a project but was getting errors.

**Comment by vrimar** [comment]
Hey folks, the project isn't dead, I'll be releasing some updates in the next few days.

**Comment by jdiderik** [comment]
Great to see you back vrimar, hope you are doing well and looking forward to some updates.

**Comment by techvio-dev** [comment]
What about now, is it dead @vrimar?
